project:
  type: book
  output-dir: docs
  render:
    ["!app/"]

book:
  title: "SEZER TURKMEN Progress Journal"
  repo-url: https://github.com/pjournal/mef07-sezerlucianturkmen
  chapters:
    - index.qmd
    - assignment1.qmd
    - inClass1.qmd
    - inClass2.qmd
    - assignment_shiny.qmd
    - ORAssignment.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]
  

format:
  html:
    theme: journal
  

